#!/bin/bash

if [[ ! -f package.json ]]; then
	echo "package.json not found. You must run $0 in the project directory."
	exit 1
fi

DIR="mapper/images"

if [ ! -d "$DIR" ]; then
	echo "Could not find target directory."
	exit 1
fi

INDEX_FILE="$DIR"/index.js

echo "// Autogenerated" > "$INDEX_FILE"
echo "const images = {" >> "$INDEX_FILE"

n_images=0

process() {
	extension="$1"
	mime="$2"

	echo "Processing: $mime"

	while read f_path; do
		i_name="$(basename "$f_path" "$extension")"
		echo "	$i_name: {image: new Promise((resolve) => {const image = new Image(); image.src = \"data:"$mime";base64,$(base64 -w 0 "$f_path")\"; resolve(image); })}," >> "$INDEX_FILE"

		echo " Written: $i_name [size: $(du --apparent-size -h "$f_path" | awk '{print $1}')]"
		n_images=$((n_images+1))
	done < <(find images -name "*$extension")
}

process .png image/png
process .svg image/svg+xml

echo "};" >> "$INDEX_FILE"
echo "export { images };" >> "$INDEX_FILE"

echo "Written $n_images image(s), output file $(du --apparent-size -h "$INDEX_FILE" | awk '{print $1}')"
