name: doc
on:
    push:
        tags:
            - v*
jobs:
    doc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: "16"
            - run: yarn
            - run: yarn run doc
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                personal_token: ${{ secrets.WORKFLOW_TOKEN }}
                external_repository: mapper1024/mapper1024.github.io
                publish_branch: master
                publish_dir: jsdoc
                destination_dir: jsdoc
