name: package
on: push
jobs:
    package-appimage-x64:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: "17"
            - run: yarn
            - run: yarn run electron-builder --x64 -l AppImage -p never
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: dist/*.AppImage
    package-linux-zip-x64:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: "17"
            - run: yarn
            - run: yarn run electron-builder --x64 -l zip -p never
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: dist/*.zip
