name: package
on:
    push:
        branches:
            - master
jobs:
    package-appimage-x64:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: "17"
            - run: yarn
            - run: yarn run electron-builder --x64 -l AppImage -p never
            - uses: actions/upload-artifact@v2
              with:
                name: AppImage
                path: dist/*.AppImage
                if-no-files-found: error
